### ISSUE TITLE
Precommit failed due to yarn missing dep

### ISSUE THREAD

**Issue by tisonkun** [GreptimeTeam/docs#720]
```
Internal Error: Greptime-Docs@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at V0.getCandidates (/Users/tison/.cache/node/corepack/yarn/3.6.1/yarn.js:435:5145)
    at kf.getCandidates (/Users/tison/.cache/node/corepack/yarn/3.6.1/yarn.js:391:1264)
    at /Users/tison/.cache/node/corepack/yarn/3.6.1/yarn.js:439:8033
    at df (/Users/tison/.cache/node/corepack/yarn/3.6.1/yarn.js:390:11070)
    at ge (/Users/tison/.cache/node/corepack/yarn/3.6.1/yarn.js:439:8013)
    at async Promise.allSettled (index 0)
    at async io (/Users/tison/.cache/node/corepack/yarn/3.6.1/yarn.js:390:10398)
    at async /Users/tison/.cache/node/corepack/yarn/3.6.1/yarn.js:439:8545
    at async ti.startProgressPromise (/Users/tison/.cache/node/corepack/yarn/3.6.1/yarn.js:390:47579)
    at async je.resolveEverything (/Users/tison/.cache/node/corepack/yarn/3.6.1/yarn.js:439:6573)
husky - commit-msg hook exited with code 1 (error)
```

Perhaps yarn3 related. But perhaps we can even drop dep on yarn. @alili

**Comment by tisonkun** [comment]
Using yarn `v1.22.19` doesn't have this issue.
